title: 'Uberlândia BitDevs'
tagline: 'BitDevs é uma comunidade para aqueles interessados em discutir e participar na pesquisa e desenvolvimento do Bitcoin e protocolos relacionados.'

menu:

  - {name: 'Eventos', url: '/events'}
  - {name: 'Meetup', url: 'https://www.meetup.com/livres-diy/', external: true}
